version: '3.1'

services:
  php:
    build: .
    volumes:
      - ./php30:/var/www/html
    ports:
      - 8085:80  
      - 3306:443  
    restart: always

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./my_database.sql:/docker-entrypoint-initdb.d/masterdd.sql
    environment:
      MYSQL_ROOT_PASSWORD: PCR2023IT
      MYSQL_DATABASE: ctc_pruebas  
      MYSQL_USER: integracion
      MYSQL_PASSWORD: PCR2023IT

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8086:80  
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: PCR2023IT
